#!/bin/bash

# Title:	library
# By: 		kingjuliando
# Tag Added:	06-06-2020
# Description:  Adds downloaded PDF documents to library folder

dlfolder="${HOME}/Downloads/*.pdf"
libfolder="${HOME}/Documents/library"

for file in ${dlfolder} ; do
  echo ${file}
  echo What would you like to rename this file before storing it?
  read newfile
  mv "${file}" "${libfolder}/${newfile}"
done
