#!/bin/bash

# Title:	add-to-path
# By: 		OfficialKingJulian
# Tag Added:	02-02-2020
# Description:  FISH; adds current dir to path

echo ""
read testing -P "Would you like to add the current location as a Path?  "

switch $testing 
  case y yes
    set -U fish_user_paths $PWD $fish_user_paths
    echo "Complete; this location is now a path!"
  case '*'
    echo "No worries, try again when you're ready!"
end

