#!/bin/bash

# Title:	show-path
# By: 		OfficialKingJulian
# Tag Added:	02-02-2020
# Description:  FISH; shows the path to help with remove-path
# https://github.com/fish-shell/fish-shell/issues/2639
echo $fish_user_paths | tr " " "\n" | nl
