#!/bin/bash

# Title:	clone-here
# By: 		OfficialKingJulian
# Tag Added:	02-02-2020
# Description:  Clone repo to the current dir

# clone
  git clone "$1"
# get cloned dir
  currdir=$(ls -t | head -1)
# cp contents
  sudo cp -r ${currdir}/* .
  sudo cp -r ${currdir}/.git .
# change permissions
  sudo chown -R julian:julian ./*
  sudo chown -R julian:julian .git
# thank you and goodbye
