#!/bin/bash

# Title:	force-pull
# By: 		kingjuliando
# Tag Added:	02-02-2020
# Description:  Forces the pull command

git fetch --all
if [[ ! -z ${1} ]] ; then
  git reset --hard origin/master
else 
  git reset --hard origin/${1}
fi
