#!/bin/bash

# Title:	nginx-wizard
# By: 		kingjuliando
# Tag Added:	14-01-2021
# Description:  A quick setup wizard for a new nginx block.

  printf "Please enter the site URL (without www.): "
  read url

  printf "Please enter the name of the main non-root user: "
  read usr

  echo "You entered ${url}."


# Creating Dir At /var/www/${url}/html
  echo "Making directory /var/www/${url}/html."
  mkdir -p /var/www/${url}/html
  chown -R ${usr}:${usr} /var/www/${url}/html
  chmod -R 755 /var/www/${url}
# Adding Ln From /var/www/${url}/html to ~/
  echo "Linking directory with user dir root."
  ln -s /var/www/${url}/html /home/${usr}/${url}

# Creating Nginx Config File For URL
  cp /home/${usr}/utils/templates/nginx-template /etc/nginx/sites-available/${url}
  sed -i -e "s/your_domain/${url}/g" /etc/nginx/sites-available/${url}
  ln -s /etc/nginx/sites-available/${url} /etc/nginx/sites-enabled/

# Restart Nginx
  systemctl restart nginx


