#!/bin/bash

# Title:	rec
# By: 		OfficialKingJulian
# Tag Added:	18-02-2020
# Description:  Thinkpad x220 Arch Screen Capture Command

ffmpeg -video_size 1366x768 -framerate 25 -f x11grab -i :0.0+0,0 ${1} 
